/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redball;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Alumno
 */
public class MainFrame extends javax.swing.JFrame {

    int count = 0;
    public static String urlGifFondoAnimado = "/imagenes/portadaAnimadaXD.gif";
    public static String urlJpgFondo = "/imagenes/portadaFijaXD.png";    
    
    private CardLayout cardLayout;
    private PanelMenuPrincipal panelMenu;
    private PanelNiveles panelNiveles;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int anchoPantalla = (int) screenSize.getWidth();
    int altoPantalla = (int) screenSize.getHeight();

    /**
     * Creates new form MenuPrincipal
     */
    public MainFrame() {
        // Obtén el tamaño de la pantalla
        this.setSize(anchoPantalla, altoPantalla);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setContentPane(new ImagenFondo());

        cardLayout = new CardLayout();
        setLayout(cardLayout);

        // Crear todos los paneles necesarios
        panelMenu = new PanelMenuPrincipal(this);
        panelNiveles = new PanelNiveles(this);

        // Agregar los paneles
        add(panelMenu, "MenuPrincipal");
        add(panelNiveles, "Niveles");

        // Mostrar los paneles
        cardLayout.show(this.getContentPane(), "MenuPrincipal");

        // Hacer visible este JFrame
        setVisible(true);
    }

    public void cambiarPanel(String panel) {
        cardLayout.show(getContentPane(), panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(224, 224, 224, 0));
        setPreferredSize(new Dimension(anchoPantalla, altoPantalla));
        setSize(getPreferredSize());
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public class ImagenFondo extends JPanel {

        private Timer timer;
        private boolean cambiarImagen;

        public ImagenFondo() {
            cambiarImagen = false;
            timer = new Timer(5000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    cambiarImagen = true;
                    repaint();
                    timer.stop();
                }
            });
            timer.start();
        }

        public void paint(Graphics g) {
            if (cambiarImagen) {
                ImageIcon fondo = new ImageIcon(getClass().getResource(urlJpgFondo)); //Ruta a la imagen JPG fija
                g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            } else {
                ImageIcon gif = new ImageIcon(getClass().getResource(urlGifFondoAnimado)); // Ruta al GIF animado
                g.drawImage(gif.getImage(), 0, 0, getWidth(), getHeight(), this);
            }

            setOpaque(false);
            super.paint(g);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}


/*
Version anterior y funcional, en la cual el JFrame y el panel estaban unidos en código:

package redball;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


public class MainFrame extends javax.swing.JFrame {
    private CardLayout cardLayout;
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int anchoPantalla = (int) screenSize.getWidth();
    int altoPantalla = (int) screenSize.getHeight();
    
    
    //direcciones de las imagenes del menu principal:
    String titulo = "/imagenesSinFondo/titulo_sinFondo.png";
    String menu = "/imagenesSinFondo/menu_sinFondo.png";
    String play = "/imagenesSinFondo/play_sinFondo.png";
    String user = "/imagenesSinFondo/user_sinFondo.png";
    
      
    public MainFrame() {
        // Obtén el tamaño de la pantalla
        
        // Establece el tamaño del JFrame para que ocupe toda la pantalla
        this.setSize(anchoPantalla, altoPantalla);

        // Insertar fondo con imágenes
        this.setContentPane(new ImagenFondo()); 
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    public void cambiarPanel(String panel) {
        cardLayout.show(getContentPane(), panel);
    }
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        User = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(anchoPantalla, altoPantalla));
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource(user)));
        User.setPreferredSize(new Dimension(anchoPantalla, 100));
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource(menu)));
        Menu.setPreferredSize(new Dimension(anchoPantalla, 100));
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource(play)));
        Play.setPreferredSize(new Dimension(anchoPantalla, 100));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        getContentPane().add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource(titulo)));
        Titulo.setPreferredSize(new Dimension(anchoPantalla, 300));
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>                        

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {                                  
        
    }                                 

    
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    
    public class ImagenFondo extends JPanel{
        
        public void paint(Graphics g){
            ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/bosqueFondo.jpg"));
            g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel User;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}


 */
