/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package redball;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javafx.embed.swing.JFXPanel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.util.Duration;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
/**
 *
 * @author saust
 */
public class PanelMenuPrincipal extends javax.swing.JPanel {
    private MainFrame mainFrame;
    int yBotonStart;
    int anchoBoton=100;
    int anchoPantalla;
    int altoPantalla;            
    int aux=20;
    
    //direcciones de las imagenes del menu principal:
    String titulo = "/imagenesSinFondo/titulo_sinFondo.png";
    String menu = "/imagenesSinFondo/menu.png";
    String play = "/imagenesSinFondo/play.png";
    String user = "/imagenesSinFondo/user.png";    
    
    // Define las coordenadas y dimensiones del rectángulo que deseas detectar
    int rectX = 100; // Cambia esto según tu necesidad
    int rectY = 350; // Cambia esto según tu necesidad
    int rectWidth = anchoPantalla; // Ancho igual al ancho de la pantalla
    int rectHeight = 100; // Cambia esto según tu necesidad
    
    /**
     * Creates new form PanelMenuPrincipal
     */                      
    public PanelMenuPrincipal(MainFrame frame) {
        this.mainFrame = frame;
        anchoPantalla=frame.anchoPantalla;
        altoPantalla=frame.altoPantalla;   
        //posicion Y en la cual el primer boton aparece:
        yBotonStart= (int)(0.41142857*frame.altoPantalla)-3;
        



//initComponents();                                                     
        Titulo = new javax.swing.JLabel();
        javax.swing.JLabel Play = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        User = new javax.swing.JLabel();

        setBackground(new Color(242, 242, 242, 0));
        setMaximumSize(new Dimension(anchoPantalla, altoPantalla));
        setMinimumSize(new Dimension(anchoPantalla, altoPantalla));
        setPreferredSize(new Dimension(anchoPantalla, altoPantalla));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setPreferredSize(new Dimension(anchoPantalla, 1));
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource(play)));
        Play.setPreferredSize(new Dimension(anchoPantalla, anchoBoton));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yBotonStart-aux, -1, -1));
        System.out.println(yBotonStart);
        
        
        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource(menu)));
        Menu.setPreferredSize(new Dimension(anchoPantalla, anchoBoton));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yBotonStart+anchoBoton+aux, -1, -1));

        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource(user)));
        User.setPreferredSize(new Dimension(anchoPantalla, anchoBoton));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, yBotonStart+((anchoBoton+aux*2)*2), -1, -1));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
        
        
        
        
        
        
        
        
    }
                    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        javax.swing.JLabel Play = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        User = new javax.swing.JLabel();

        setBackground(new Color(242, 242, 242, 0));
        setMaximumSize(new Dimension(anchoPantalla, altoPantalla));
        setMinimumSize(new Dimension(anchoPantalla, altoPantalla));
        setPreferredSize(new Dimension(anchoPantalla, altoPantalla));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setPreferredSize(new Dimension(anchoPantalla, 300));
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource(play)));
        Play.setPreferredSize(new Dimension(anchoPantalla, 100));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource(menu)));
        Menu.setPreferredSize(new Dimension(anchoPantalla, 100));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource(user)));
        User.setPreferredSize(new Dimension(anchoPantalla, 100));
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        mainFrame.cambiarPanel("Niveles");
    }//GEN-LAST:event_PlayMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        //mainFrame.cambiarPanel("Niveles");
    }//GEN-LAST:event_MenuMouseClicked

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        //mainFrame.cambiarPanel("Niveles");
    }//GEN-LAST:event_UserMouseClicked


    /*@Override
    public void paint(Graphics g){
        ImageIcon fondo = new ImageIcon(getClass().getResource("/imagenes/bosqueFondo.jpg"));
        g.drawImage(fondo.getImage(), 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        //super.paint(g);
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel User;
    // End of variables declaration//GEN-END:variables
}
